### ISSUE TITLE
/target_mac responds with text/plain MIME type, but sends binary data

### ISSUE THREAD

**Issue by swarren** [solarkennedy/ether_housed#1]
$ wget -O /dev/stdout 'http://etherhouse.xkyle.com/target_mac?id=1&api_key=xxx' | hexdump -C
...
Length: 6 [text/plain]
...
[hexdump shows binary data]

Perhaps this is due to converting the MAC address to a string type:

func target_mac_handler(res http.ResponseWriter, req *http.Request) {
... if validate_key(api_key, int(house_id)) {
        target_mac := Common.target_mac[house_id]
        target_mac_binary := mactobinary(target_mac)
        target_mac_string := string(target_mac_binary[:6])

Does removing that final line still work, and fix the MIME type?

FWIW, the /state request gets this right and indicates a MIME type of application/octet-stream, presumably because it explicitly writes a byte array:

```
    tmp_bytes := []byte{byte(state_value)}
    res.Write(tmp_bytes)
```

**Comment by solarkennedy** [comment]
doing a res.Write directly... still makes this one end up being text-plain.

Apparently there is and auto-detect going on: http://golang.org/src/net/http/sniff.go?s=648:690#L11

I've gone ahead and made it write directly anyway, and set an explicit header for octet-stream on those endpoints that are binary.

**Comment by solarkennedy** [comment]
Thanks!
